version: "3.9"
services:
    my_hex_app:
      environment:
        - NODE_ENV=production
      build: .
      ports:
        - "8000:8000"
      env_file:
        - .env.${NODE_ENV}
      command: npm start
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
